services:
  - type: web
    name: amaliyot-exam
    env: python
    buildCommand: |
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.13

static:
  - type: static
    name: static
    path: staticfiles
